version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.4
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

  spark-master:
    image: bitnami/spark:3.4
    environment:
      - SPARK_MODE=master
    ports:
      - "4040:4040"
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      - kafka

  producer:
    build:
      context: .
      dockerfile: archi_docker/dockerfile.producer
    depends_on:
      - kafka
    env_file: .env

  api:
    build:
      context: .
      dockerfile: archi_docker/dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - kafka

  trans_load:
    build:
      context: .
      dockerfile: archi_docker/dockerfile.spark
    depends_on:
      - kafka
      - spark-master
    env_file: .env
