version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    mem_limit: 512m

  kafka:
    image: bitnami/kafka:3.4
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    mem_limit: 1g

  spark-master:
    image: bitnami/spark:3.4
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_DAEMON_MEMORY=1g
    ports:
      - "8080:8080"
      - "7077:7077"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tuln | grep 7077 || ss -tuln | grep 7077"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark-worker:
    image: bitnami/spark:3.4
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_DAEMON_MEMORY=1G
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    healthcheck:
      test: ["CMD-SHELL", "netstat -tuln | grep 8081 || ss -tuln | grep 8081"]
      interval: 20s
      timeout: 10s
      retries: 5

  trans_load:
    build:
      context: .
      dockerfile: archi_docker/dockerfile.spark
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - PYTHONUNBUFFERED=1
      - PYSPARK_PYTHON=/opt/bitnami/python/bin/python
      - PYSPARK_DRIVER_PYTHON=/opt/bitnami/python/bin/python
      - PATH=$PATH:/.local/bin
    depends_on:
      spark-master:
        condition: service_healthy
      spark-worker:
        condition: service_healthy
      kafka:
        condition: service_started
    env_file: .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    restart: on-failure

  producer:
    build:
      context: .
      dockerfile: archi_docker/dockerfile.producer
    depends_on:
      kafka:
        condition: service_started
    env_file: .env
    mem_limit: 512m
    restart: on-failure

  api:
    build:
      context: .
      dockerfile: archi_docker/dockerfile.api
    environment:
      - TOKENIZERS_PARALLELISM=false
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    deploy:
      resources:
        limits:
          memory: 2G
    restart: unless-stopped
