FROM python:3.10-slim
WORKDIR /app

RUN apt-get update \
 && apt-get install -y --no-install-recommends gcc \
 && rm -rf /var/lib/apt/lists/*

COPY requirement.producer.txt ./requirement.producer.txt
RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirement.producer.txt \
 && rm -rf ~/.cache/pip

COPY extract.py ./

CMD ["python", "extract.py"]
