FROM python:3.10-slim

WORKDIR /app

COPY archi_docker/requirement.producer.txt ./requirements.txt
RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

COPY app/extract.py ./extract.py
CMD ["python", "extract.py"]
