
FROM python:3.10-slim


WORKDIR /app


COPY ./app/extract.py /app/extract.py
COPY ./requirements.txt /app/requirements.txt


RUN pip install --no-cache-dir -r /app/requirements.txt


CMD ["python", "extract.py"]
