FROM python:3.10-slim

WORKDIR /app

COPY ./app /app
COPY ./archi_docker/requirement.producer.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

CMD ["python", "extract.py"]
