
FROM python:3.10-slim


WORKDIR /app


COPY ./app/api.py /app/api.py
COPY ./requirements.txt /app/requirements.txt


RUN pip install --no-cache-dir -r /app/requirements.txt


CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
